### ISSUE TITLE
Readjust the layout

### ISSUE THREAD

**Issue by Scoombe** [Scoombe/react-typing#1]
The layout needs working on so that when the window is smaller the top 3 columns are the same size.

It also needs to be changed so that the text is in the middle of the page.

**Comment by ummahusla** [comment]
@Scoombe Fancy adding a [reactstrap](http://reactstrap.github.io)

**Comment by Scoombe** [comment]
@ummahusla I was using [react semantic](https://react.semantic-ui.com/). There is a [grid](https://react.semantic-ui.com/collections/grid/) on there.

**Comment by ummahusla** [comment]
@Scoombe Cool, will take a look at it, can you assign it to me?

**Comment by Scoombe** [comment]
@ummahusla I can't seem to assign you.
