### ISSUE TITLE
Add a component for the finishing of the test

### ISSUE THREAD

**Issue by Scoombe** [Scoombe/react-typing#3]
This needs to display the score the user got. 

And give the option to play again.

**Comment by sammygriffiths** [comment]
I'll give this one a go.

**Comment by Scoombe** [comment]
@sammygriffiths awesome! Let me know if you need help.

**Comment by sammygriffiths** [comment]
Sorry @seal62 I've already completed it, although I'm happy to take any suggestions from you and @Scoombe on my PRs.
