### ISSUE TITLE
Project architecture can be improved

### ISSUE THREAD

**Issue by ummahusla** [Scoombe/react-typing#4]
I had a quick look at the project architecture and yet I was impressed by the fact how poorly it's structured. 

I can take care of it, and submit a few PRs later on with my suggestions.

**Comment by ummahusla** [comment]
@Scoombe If you are happy for me to do, please assign it to me and add `hacktoberfest` tag, thanks.

**Comment by Scoombe** [comment]
#9 @ummahusla  I've made some slight changes to the structure.

**Comment by Scoombe** [comment]
closing since I think it's been fixed now. 
@ummahusla have a look, if there are more changes needed raise a new issue.
