### ISSUE TITLE
add some tests

### ISSUE THREAD

**Issue by Scoombe** [Scoombe/react-typing#7]
Add some tests to the page. that.

**Comment by Fabianopb** [comment]
Hi @Scoombe, if you mean creating a test suite I could take a look, I've been working a lot with Jest and Enzyme recently.

**Comment by Scoombe** [comment]
@Fabianopb Hi that would be perfect. I haven't looked much into test with react. Would be really handy if you could have a go!

**Comment by Fabianopb** [comment]
Sounds great, I can make a PR later today with the whole set up to use Jest with Enzyme for testing components!

**Comment by Fabianopb** [comment]
PR created: https://github.com/Scoombe/react-typing/pull/10

**Comment by ummahusla** [comment]
@Scoombe @Fabianopb Left a comment for #10

**Comment by Fabianopb** [comment]
Great, PR merged! Issue can be closed! ;)
